@startuml
class ResNet9 {
  +forward(x)
  +load_state_dict()
}

class predict_image {
  +predict_image(img, model)
}

class FlaskApp {
  +home()
  +about()
  +contact()
  +disease_prediction()
  +fertilizer_recommendation()
  +crop_recommend()
}

FlaskApp --> predict_image
predict_image --> ResNet9
@enduml
